### ISSUE TITLE
Getting error Index Out of range while query

### ISSUE THREAD

**Issue by aniketpant1** [jeffvestal/ElasticDocs_GPT#5]
Hi @jeffvestal ,

I am getting this below error. I am following your steps
![image](https://github.com/jeffvestal/ElasticDocs_GPT/assets/40541079/cf6ca543-7935-4a52-9802-15d476f20a6c)

**Comment by aniketpant1** [comment]
Can anyone please help me my trail period will end in this week

**Comment by mrmutator** [comment]
I had the same problem. I fixed it by modifying the filter in the search query slightly:

```
            "filter": [{
                "exists": {
                    "field": "elastic-docs_title-vector"
                }
            }]
```
I. e. use the field "elastic-docs_title-vector" instead of only "title-vector".
Not sure if the vector search actually works correctly, but at least search returns some hits.
